export enum ActivityType {
    WATERING = 'WATERING',
    PLANTING = 'PLANTING',
    FISHING = 'FISHING',
    SMITHING = 'SMITHING',
    SMELTING = 'SMELTING',
    COOKING = 'COOKING',
    LUMBERING = 'LUMBERING',
    MINING = 'MINING',
    COMBAT = 'COMBAT',
    HATCHING = 'HATCHING',
    OFFERING = 'OFFERING'
}

export enum TaskStatus {
  IDLE = 'IDLE',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}